"""create inventory and stock table

Revision ID: 258fd0c8afc3
Revises:
Create Date: 2026-10-03 23:45:23.843742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "258fd0c8afc3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_inventory_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_quantity <= quantity",
            name=op.f("ck_inventory_reserved_lte_quantity"),
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0",
            name=op.f("ck_inventory_reserved_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory")),
    )
    op.create_index(
        op.f("ix_inventory_product_id"),
        "inventory",
        ["product_id"],
        unique=True,
    )
    op.create_table(
        "stock_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RESERVED",
                "CONFIRMED",
                "RELEASED",
                "EXPIRED",
                "FAILED",
                name="reservation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_reservations")),
    )
    op.create_index(
        op.f("ix_stock_reservations_order_id"),
        "stock_reservations",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_reservations_product_id"),
        "stock_reservations",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_reservations_product_id"),
        table_name="stock_reservations",
    )
    op.drop_index(
        op.f("ix_stock_reservations_order_id"), table_name="stock_reservations"
    )
    op.drop_table("stock_reservations")
    op.drop_index(op.f("ix_inventory_product_id"), table_name="inventory")
    op.drop_table("inventory")
    # ### end Alembic commands ###
